-- ============================================
-- 增加企业评论表 (supabase-add-company-comments.sql)
-- ============================================

-- 1. 创建企业评论表
create table if not exists company_comments (
  id bigint generated by default as identity primary key,
  company_id int not null,
  content text not null,
  rating int default 5 check (rating >= 1 and rating <= 5),
  user_id uuid references auth.users(id),
  user_email text,
  created_at timestamp with time zone default now()
);

-- 2. 开启行级安全 (RLS)
alter table company_comments enable row level security;

-- 3. 策略：允许公开读取
create policy "Public can view company comments" on company_comments for select using (true);

-- 4. 策略：允许登录用户插入
create policy "Users can create company comments" on company_comments for insert with check (auth.role() = 'authenticated');
