-- ============================================
-- 增加互动功能表 (supabase-add-interaction.sql)
-- ============================================

-- 1. 创建点赞表
create table if not exists user_likes (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  target_type text not null check (target_type in ('article', 'company')),
  target_id bigint not null,
  created_at timestamp with time zone default now(),
  unique(user_id, target_type, target_id) -- 防止重复点赞
);

-- 2. 创建收藏表
create table if not exists user_favorites (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  target_type text not null check (target_type in ('article', 'company')),
  target_id bigint not null,
  created_at timestamp with time zone default now(),
  unique(user_id, target_type, target_id) -- 防止重复收藏
);

-- 3. 开启行级安全 (RLS)
alter table user_likes enable row level security;
alter table user_favorites enable row level security;

-- 4. 设置策略：用户只能操作自己的数据
create policy "Users can manage their own likes" on user_likes for all using (auth.uid() = user_id);
create policy "Users can manage their own favorites" on user_favorites for all using (auth.uid() = user_id);

-- 5. 策略：允许公开读取（用于显示点赞数/收藏状态）
create policy "Public can read likes" on user_likes for select using (true);
create policy "Public can read favorites" on user_favorites for select using (true);
