-- 搜索统计表 (supabase-add-search-stats.sql)
-- 用于记录用户搜索行为，帮助分析热门关键词

create table if not exists search_stats (
  id bigint generated by default as identity primary key,
  query text not null,
  results_count int default 0,
  user_id uuid references auth.users(id),
  created_at timestamp with time zone default now()
);

-- 开启 RLS
alter table search_stats enable row level security;

-- 策略：仅管理员可查看所有统计
create policy "Admins can view search stats" on search_stats for select using (true);
create policy "Anyone can insert search stats" on search_stats for insert with check (true);

-- 热门关键词视图（最近 7 天 Top 20）
create or replace view top_searches as
select 
  query,
  count(*) as search_count,
  avg(results_count)::int as avg_results
from search_stats
where created_at > now() - interval '7 days'
group by query
order by search_count desc
limit 20;
