# P2-2 标签体系 SQL 脚本
# 在 Supabase SQL Editor 运行

-- 1. 创建标签表
create table if not exists tags (
  id bigint generated by default as identity primary key,
  name text not null unique,
  color text default '#007aff',
  created_at timestamp with time zone default now()
);

-- 2. 创建文章-标签关联表（多对多）
create table if not exists article_tags (
  article_id bigint references articles(id) on delete cascade,
  tag_id bigint references tags(id) on delete cascade,
  primary key (article_id, tag_id)
);

-- 3. 开启 RLS
alter table tags enable row level security;
alter table article_tags enable row level security;

-- 4. 策略：所有人可读
create policy "Public can view tags" on tags for select using (true);
create policy "Public can view article_tags" on article_tags for select using (true);

-- 5. 策略：登录用户可管理
create policy "Authenticated can manage tags" on tags for all using (auth.role() = 'authenticated');
create policy "Authenticated can manage article_tags" on article_tags for all using (auth.role() = 'authenticated');

-- 6. 为已有文章添加默认分类标签（可选）
-- insert into tags (name, color) values ('技术', '#007aff'), ('生活', '#34c759'), ('随笔', '#ff9500') on conflict (name) do nothing;
