-- P2-5 仪表盘实时数据 SQL
-- 如果 search_stats 表不存在，请运行以下 SQL 创建

create table if not exists search_stats (
  id bigint generated by default as identity primary key,
  query text not null,
  results_count integer default 0,
  created_at timestamp with time zone default now()
);

-- 开启 RLS
alter table search_stats enable row level security;

-- 策略：所有人可读（统计用）
create policy "Public can view search_stats" on search_stats for select using (true);

-- 策略：登录用户可写入
create policy "Authenticated can insert search_stats" on search_stats for insert with check (auth.role() = 'authenticated');
